# Generated by Django 4.2 on 2024-12-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_article_created_at_article_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
